package com.lab.sdt.dao;

import com.lab.sdt.model.EnfermedadPaciente;
import com.lab.sdt.model.EnfermedadPacienteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EnfermedadPacienteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enfermedad_paciente
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    long countByExample(EnfermedadPacienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enfermedad_paciente
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int deleteByExample(EnfermedadPacienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enfermedad_paciente
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int deleteByPrimaryKey(Integer idenfermedadPaciente);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enfermedad_paciente
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int insert(EnfermedadPaciente record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enfermedad_paciente
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int insertSelective(EnfermedadPaciente record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enfermedad_paciente
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    List<EnfermedadPaciente> selectByExample(EnfermedadPacienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enfermedad_paciente
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    EnfermedadPaciente selectByPrimaryKey(Integer idenfermedadPaciente);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enfermedad_paciente
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByExampleSelective(@Param("record") EnfermedadPaciente record, @Param("example") EnfermedadPacienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enfermedad_paciente
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByExample(@Param("record") EnfermedadPaciente record, @Param("example") EnfermedadPacienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enfermedad_paciente
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByPrimaryKeySelective(EnfermedadPaciente record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enfermedad_paciente
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByPrimaryKey(EnfermedadPaciente record);
}