package com.lab.sdt.dao;

import com.lab.sdt.model.Equipo;
import com.lab.sdt.model.EquipoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EquipoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    long countByExample(EquipoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int deleteByExample(EquipoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int deleteByPrimaryKey(Integer idequipo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int insert(Equipo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int insertSelective(Equipo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    List<Equipo> selectByExample(EquipoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    Equipo selectByPrimaryKey(Integer idequipo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByExampleSelective(@Param("record") Equipo record, @Param("example") EquipoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByExample(@Param("record") Equipo record, @Param("example") EquipoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByPrimaryKeySelective(Equipo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByPrimaryKey(Equipo record);
}