package com.lab.sdt.dao;

import com.lab.sdt.model.Especialidad;
import com.lab.sdt.model.EspecialidadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EspecialidadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table especialidad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    long countByExample(EspecialidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table especialidad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int deleteByExample(EspecialidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table especialidad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int deleteByPrimaryKey(Integer idespecialidad);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table especialidad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int insert(Especialidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table especialidad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int insertSelective(Especialidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table especialidad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    List<Especialidad> selectByExample(EspecialidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table especialidad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    Especialidad selectByPrimaryKey(Integer idespecialidad);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table especialidad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByExampleSelective(@Param("record") Especialidad record, @Param("example") EspecialidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table especialidad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByExample(@Param("record") Especialidad record, @Param("example") EspecialidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table especialidad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByPrimaryKeySelective(Especialidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table especialidad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByPrimaryKey(Especialidad record);
}