package com.lab.sdt.dao;

import com.lab.sdt.model.Estado;
import com.lab.sdt.model.EstadoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EstadoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    long countByExample(EstadoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int deleteByExample(EstadoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int deleteByPrimaryKey(Integer idestado);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int insert(Estado record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int insertSelective(Estado record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    List<Estado> selectByExample(EstadoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    Estado selectByPrimaryKey(Integer idestado);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByExampleSelective(@Param("record") Estado record, @Param("example") EstadoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByExample(@Param("record") Estado record, @Param("example") EstadoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByPrimaryKeySelective(Estado record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByPrimaryKey(Estado record);
}