package com.lab.sdt.dao;

import com.lab.sdt.model.ExpeEstim;
import com.lab.sdt.model.ExpeEstimExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpeEstimMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expe_estim
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    long countByExample(ExpeEstimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expe_estim
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int deleteByExample(ExpeEstimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expe_estim
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int deleteByPrimaryKey(Integer idexestim);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expe_estim
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int insert(ExpeEstim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expe_estim
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int insertSelective(ExpeEstim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expe_estim
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    List<ExpeEstim> selectByExample(ExpeEstimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expe_estim
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    ExpeEstim selectByPrimaryKey(Integer idexestim);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expe_estim
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByExampleSelective(@Param("record") ExpeEstim record, @Param("example") ExpeEstimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expe_estim
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByExample(@Param("record") ExpeEstim record, @Param("example") ExpeEstimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expe_estim
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByPrimaryKeySelective(ExpeEstim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expe_estim
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByPrimaryKey(ExpeEstim record);
}