package com.lab.sdt.dao;

import com.lab.sdt.model.Grado;
import com.lab.sdt.model.GradoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GradoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    long countByExample(GradoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int deleteByExample(GradoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int deleteByPrimaryKey(Integer idgrado);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int insert(Grado record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int insertSelective(Grado record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    List<Grado> selectByExample(GradoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    Grado selectByPrimaryKey(Integer idgrado);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByExampleSelective(@Param("record") Grado record, @Param("example") GradoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByExample(@Param("record") Grado record, @Param("example") GradoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByPrimaryKeySelective(Grado record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByPrimaryKey(Grado record);
}