package com.lab.sdt.dao;

import com.lab.sdt.model.NumOnda;
import com.lab.sdt.model.NumOndaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NumOndaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table num_onda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    long countByExample(NumOndaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table num_onda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int deleteByExample(NumOndaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table num_onda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int deleteByPrimaryKey(Integer idnumOnda);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table num_onda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int insert(NumOnda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table num_onda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int insertSelective(NumOnda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table num_onda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    List<NumOnda> selectByExample(NumOndaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table num_onda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    NumOnda selectByPrimaryKey(Integer idnumOnda);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table num_onda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByExampleSelective(@Param("record") NumOnda record, @Param("example") NumOndaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table num_onda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByExample(@Param("record") NumOnda record, @Param("example") NumOndaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table num_onda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByPrimaryKeySelective(NumOnda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table num_onda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByPrimaryKey(NumOnda record);
}