package com.lab.sdt.dao;

import com.lab.sdt.model.OndaValor;
import com.lab.sdt.model.OndaValorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OndaValorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    long countByExample(OndaValorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int deleteByExample(OndaValorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int deleteByPrimaryKey(Integer idondavalor);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int insert(OndaValor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int insertSelective(OndaValor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    List<OndaValor> selectByExample(OndaValorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    OndaValor selectByPrimaryKey(Integer idondavalor);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByExampleSelective(@Param("record") OndaValor record, @Param("example") OndaValorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByExample(@Param("record") OndaValor record, @Param("example") OndaValorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByPrimaryKeySelective(OndaValor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    int updateByPrimaryKey(OndaValor record);
}