package com.lab.sdt.model;

public class Correlacion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column correlacion.idCorrelacion
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idcorrelacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column correlacion.correlacion
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String correlacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column correlacion.idFoto
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idfoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column correlacion.idPaciente
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idpaciente;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column correlacion.idCorrelacion
     *
     * @return the value of correlacion.idCorrelacion
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdcorrelacion() {
        return idcorrelacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column correlacion.idCorrelacion
     *
     * @param idcorrelacion the value for correlacion.idCorrelacion
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdcorrelacion(Integer idcorrelacion) {
        this.idcorrelacion = idcorrelacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column correlacion.correlacion
     *
     * @return the value of correlacion.correlacion
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getCorrelacion() {
        return correlacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column correlacion.correlacion
     *
     * @param correlacion the value for correlacion.correlacion
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setCorrelacion(String correlacion) {
        this.correlacion = correlacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column correlacion.idFoto
     *
     * @return the value of correlacion.idFoto
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdfoto() {
        return idfoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column correlacion.idFoto
     *
     * @param idfoto the value for correlacion.idFoto
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdfoto(Integer idfoto) {
        this.idfoto = idfoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column correlacion.idPaciente
     *
     * @return the value of correlacion.idPaciente
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdpaciente() {
        return idpaciente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column correlacion.idPaciente
     *
     * @param idpaciente the value for correlacion.idPaciente
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdpaciente(Integer idpaciente) {
        this.idpaciente = idpaciente;
    }
}