package com.lab.sdt.model;

public class Enfermedad {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enfermedad.idEnfermedad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idenfermedad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enfermedad.enfermedad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String enfermedad;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enfermedad.idEnfermedad
     *
     * @return the value of enfermedad.idEnfermedad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdenfermedad() {
        return idenfermedad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enfermedad.idEnfermedad
     *
     * @param idenfermedad the value for enfermedad.idEnfermedad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdenfermedad(Integer idenfermedad) {
        this.idenfermedad = idenfermedad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enfermedad.enfermedad
     *
     * @return the value of enfermedad.enfermedad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getEnfermedad() {
        return enfermedad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enfermedad.enfermedad
     *
     * @param enfermedad the value for enfermedad.enfermedad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setEnfermedad(String enfermedad) {
        this.enfermedad = enfermedad;
    }
}