package com.lab.sdt.model;

import java.util.ArrayList;
import java.util.List;

public class EquipoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public EquipoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdequipoIsNull() {
            addCriterion("idEquipo is null");
            return (Criteria) this;
        }

        public Criteria andIdequipoIsNotNull() {
            addCriterion("idEquipo is not null");
            return (Criteria) this;
        }

        public Criteria andIdequipoEqualTo(Integer value) {
            addCriterion("idEquipo =", value, "idequipo");
            return (Criteria) this;
        }

        public Criteria andIdequipoNotEqualTo(Integer value) {
            addCriterion("idEquipo <>", value, "idequipo");
            return (Criteria) this;
        }

        public Criteria andIdequipoGreaterThan(Integer value) {
            addCriterion("idEquipo >", value, "idequipo");
            return (Criteria) this;
        }

        public Criteria andIdequipoGreaterThanOrEqualTo(Integer value) {
            addCriterion("idEquipo >=", value, "idequipo");
            return (Criteria) this;
        }

        public Criteria andIdequipoLessThan(Integer value) {
            addCriterion("idEquipo <", value, "idequipo");
            return (Criteria) this;
        }

        public Criteria andIdequipoLessThanOrEqualTo(Integer value) {
            addCriterion("idEquipo <=", value, "idequipo");
            return (Criteria) this;
        }

        public Criteria andIdequipoIn(List<Integer> values) {
            addCriterion("idEquipo in", values, "idequipo");
            return (Criteria) this;
        }

        public Criteria andIdequipoNotIn(List<Integer> values) {
            addCriterion("idEquipo not in", values, "idequipo");
            return (Criteria) this;
        }

        public Criteria andIdequipoBetween(Integer value1, Integer value2) {
            addCriterion("idEquipo between", value1, value2, "idequipo");
            return (Criteria) this;
        }

        public Criteria andIdequipoNotBetween(Integer value1, Integer value2) {
            addCriterion("idEquipo not between", value1, value2, "idequipo");
            return (Criteria) this;
        }

        public Criteria andNoserieIsNull() {
            addCriterion("noSerie is null");
            return (Criteria) this;
        }

        public Criteria andNoserieIsNotNull() {
            addCriterion("noSerie is not null");
            return (Criteria) this;
        }

        public Criteria andNoserieEqualTo(String value) {
            addCriterion("noSerie =", value, "noserie");
            return (Criteria) this;
        }

        public Criteria andNoserieNotEqualTo(String value) {
            addCriterion("noSerie <>", value, "noserie");
            return (Criteria) this;
        }

        public Criteria andNoserieGreaterThan(String value) {
            addCriterion("noSerie >", value, "noserie");
            return (Criteria) this;
        }

        public Criteria andNoserieGreaterThanOrEqualTo(String value) {
            addCriterion("noSerie >=", value, "noserie");
            return (Criteria) this;
        }

        public Criteria andNoserieLessThan(String value) {
            addCriterion("noSerie <", value, "noserie");
            return (Criteria) this;
        }

        public Criteria andNoserieLessThanOrEqualTo(String value) {
            addCriterion("noSerie <=", value, "noserie");
            return (Criteria) this;
        }

        public Criteria andNoserieLike(String value) {
            addCriterion("noSerie like", value, "noserie");
            return (Criteria) this;
        }

        public Criteria andNoserieNotLike(String value) {
            addCriterion("noSerie not like", value, "noserie");
            return (Criteria) this;
        }

        public Criteria andNoserieIn(List<String> values) {
            addCriterion("noSerie in", values, "noserie");
            return (Criteria) this;
        }

        public Criteria andNoserieNotIn(List<String> values) {
            addCriterion("noSerie not in", values, "noserie");
            return (Criteria) this;
        }

        public Criteria andNoserieBetween(String value1, String value2) {
            addCriterion("noSerie between", value1, value2, "noserie");
            return (Criteria) this;
        }

        public Criteria andNoserieNotBetween(String value1, String value2) {
            addCriterion("noSerie not between", value1, value2, "noserie");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNull() {
            addCriterion("estado is null");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNotNull() {
            addCriterion("estado is not null");
            return (Criteria) this;
        }

        public Criteria andEstadoEqualTo(String value) {
            addCriterion("estado =", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotEqualTo(String value) {
            addCriterion("estado <>", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThan(String value) {
            addCriterion("estado >", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThanOrEqualTo(String value) {
            addCriterion("estado >=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThan(String value) {
            addCriterion("estado <", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThanOrEqualTo(String value) {
            addCriterion("estado <=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLike(String value) {
            addCriterion("estado like", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotLike(String value) {
            addCriterion("estado not like", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoIn(List<String> values) {
            addCriterion("estado in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotIn(List<String> values) {
            addCriterion("estado not in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoBetween(String value1, String value2) {
            addCriterion("estado between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotBetween(String value1, String value2) {
            addCriterion("estado not between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andOndapredeterminadaIsNull() {
            addCriterion("ondaPredeterminada is null");
            return (Criteria) this;
        }

        public Criteria andOndapredeterminadaIsNotNull() {
            addCriterion("ondaPredeterminada is not null");
            return (Criteria) this;
        }

        public Criteria andOndapredeterminadaEqualTo(String value) {
            addCriterion("ondaPredeterminada =", value, "ondapredeterminada");
            return (Criteria) this;
        }

        public Criteria andOndapredeterminadaNotEqualTo(String value) {
            addCriterion("ondaPredeterminada <>", value, "ondapredeterminada");
            return (Criteria) this;
        }

        public Criteria andOndapredeterminadaGreaterThan(String value) {
            addCriterion("ondaPredeterminada >", value, "ondapredeterminada");
            return (Criteria) this;
        }

        public Criteria andOndapredeterminadaGreaterThanOrEqualTo(String value) {
            addCriterion("ondaPredeterminada >=", value, "ondapredeterminada");
            return (Criteria) this;
        }

        public Criteria andOndapredeterminadaLessThan(String value) {
            addCriterion("ondaPredeterminada <", value, "ondapredeterminada");
            return (Criteria) this;
        }

        public Criteria andOndapredeterminadaLessThanOrEqualTo(String value) {
            addCriterion("ondaPredeterminada <=", value, "ondapredeterminada");
            return (Criteria) this;
        }

        public Criteria andOndapredeterminadaLike(String value) {
            addCriterion("ondaPredeterminada like", value, "ondapredeterminada");
            return (Criteria) this;
        }

        public Criteria andOndapredeterminadaNotLike(String value) {
            addCriterion("ondaPredeterminada not like", value, "ondapredeterminada");
            return (Criteria) this;
        }

        public Criteria andOndapredeterminadaIn(List<String> values) {
            addCriterion("ondaPredeterminada in", values, "ondapredeterminada");
            return (Criteria) this;
        }

        public Criteria andOndapredeterminadaNotIn(List<String> values) {
            addCriterion("ondaPredeterminada not in", values, "ondapredeterminada");
            return (Criteria) this;
        }

        public Criteria andOndapredeterminadaBetween(String value1, String value2) {
            addCriterion("ondaPredeterminada between", value1, value2, "ondapredeterminada");
            return (Criteria) this;
        }

        public Criteria andOndapredeterminadaNotBetween(String value1, String value2) {
            addCriterion("ondaPredeterminada not between", value1, value2, "ondapredeterminada");
            return (Criteria) this;
        }

        public Criteria andTipoIsNull() {
            addCriterion("tipo is null");
            return (Criteria) this;
        }

        public Criteria andTipoIsNotNull() {
            addCriterion("tipo is not null");
            return (Criteria) this;
        }

        public Criteria andTipoEqualTo(String value) {
            addCriterion("tipo =", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotEqualTo(String value) {
            addCriterion("tipo <>", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoGreaterThan(String value) {
            addCriterion("tipo >", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoGreaterThanOrEqualTo(String value) {
            addCriterion("tipo >=", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoLessThan(String value) {
            addCriterion("tipo <", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoLessThanOrEqualTo(String value) {
            addCriterion("tipo <=", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoLike(String value) {
            addCriterion("tipo like", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotLike(String value) {
            addCriterion("tipo not like", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoIn(List<String> values) {
            addCriterion("tipo in", values, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotIn(List<String> values) {
            addCriterion("tipo not in", values, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoBetween(String value1, String value2) {
            addCriterion("tipo between", value1, value2, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotBetween(String value1, String value2) {
            addCriterion("tipo not between", value1, value2, "tipo");
            return (Criteria) this;
        }

        public Criteria andEstatusIsNull() {
            addCriterion("estatus is null");
            return (Criteria) this;
        }

        public Criteria andEstatusIsNotNull() {
            addCriterion("estatus is not null");
            return (Criteria) this;
        }

        public Criteria andEstatusEqualTo(String value) {
            addCriterion("estatus =", value, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusNotEqualTo(String value) {
            addCriterion("estatus <>", value, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusGreaterThan(String value) {
            addCriterion("estatus >", value, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusGreaterThanOrEqualTo(String value) {
            addCriterion("estatus >=", value, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusLessThan(String value) {
            addCriterion("estatus <", value, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusLessThanOrEqualTo(String value) {
            addCriterion("estatus <=", value, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusLike(String value) {
            addCriterion("estatus like", value, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusNotLike(String value) {
            addCriterion("estatus not like", value, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusIn(List<String> values) {
            addCriterion("estatus in", values, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusNotIn(List<String> values) {
            addCriterion("estatus not in", values, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusBetween(String value1, String value2) {
            addCriterion("estatus between", value1, value2, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusNotBetween(String value1, String value2) {
            addCriterion("estatus not between", value1, value2, "estatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table equipo
     *
     * @mbg.generated do_not_delete_during_merge Mon May 20 14:45:29 CDT 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table equipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}