package com.lab.sdt.model;

public class Equipo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipo.idEquipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idequipo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipo.noSerie
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String noserie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipo.estado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String estado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipo.ondaPredeterminada
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String ondapredeterminada;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipo.tipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String tipo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipo.estatus
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String estatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipo.idEquipo
     *
     * @return the value of equipo.idEquipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdequipo() {
        return idequipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipo.idEquipo
     *
     * @param idequipo the value for equipo.idEquipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdequipo(Integer idequipo) {
        this.idequipo = idequipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipo.noSerie
     *
     * @return the value of equipo.noSerie
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getNoserie() {
        return noserie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipo.noSerie
     *
     * @param noserie the value for equipo.noSerie
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setNoserie(String noserie) {
        this.noserie = noserie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipo.estado
     *
     * @return the value of equipo.estado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipo.estado
     *
     * @param estado the value for equipo.estado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipo.ondaPredeterminada
     *
     * @return the value of equipo.ondaPredeterminada
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getOndapredeterminada() {
        return ondapredeterminada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipo.ondaPredeterminada
     *
     * @param ondapredeterminada the value for equipo.ondaPredeterminada
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setOndapredeterminada(String ondapredeterminada) {
        this.ondapredeterminada = ondapredeterminada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipo.tipo
     *
     * @return the value of equipo.tipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipo.tipo
     *
     * @param tipo the value for equipo.tipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipo.estatus
     *
     * @return the value of equipo.estatus
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getEstatus() {
        return estatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipo.estatus
     *
     * @param estatus the value for equipo.estatus
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
}