package com.lab.sdt.model;

public class EquipoManten {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipo_manten.idEquipo_manten
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idequipoManten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipo_manten.idEquipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idequipo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipo_manten.idMantenimiento
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idmantenimiento;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipo_manten.idEquipo_manten
     *
     * @return the value of equipo_manten.idEquipo_manten
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdequipoManten() {
        return idequipoManten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipo_manten.idEquipo_manten
     *
     * @param idequipoManten the value for equipo_manten.idEquipo_manten
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdequipoManten(Integer idequipoManten) {
        this.idequipoManten = idequipoManten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipo_manten.idEquipo
     *
     * @return the value of equipo_manten.idEquipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdequipo() {
        return idequipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipo_manten.idEquipo
     *
     * @param idequipo the value for equipo_manten.idEquipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdequipo(Integer idequipo) {
        this.idequipo = idequipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipo_manten.idMantenimiento
     *
     * @return the value of equipo_manten.idMantenimiento
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdmantenimiento() {
        return idmantenimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipo_manten.idMantenimiento
     *
     * @param idmantenimiento the value for equipo_manten.idMantenimiento
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdmantenimiento(Integer idmantenimiento) {
        this.idmantenimiento = idmantenimiento;
    }
}