package com.lab.sdt.model;

public class Especialidad {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column especialidad.idEspecialidad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idespecialidad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column especialidad.especialidad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String especialidad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column especialidad.idGrado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idgrado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column especialidad.idUsuario
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idusuario;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column especialidad.idEspecialidad
     *
     * @return the value of especialidad.idEspecialidad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdespecialidad() {
        return idespecialidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column especialidad.idEspecialidad
     *
     * @param idespecialidad the value for especialidad.idEspecialidad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdespecialidad(Integer idespecialidad) {
        this.idespecialidad = idespecialidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column especialidad.especialidad
     *
     * @return the value of especialidad.especialidad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getEspecialidad() {
        return especialidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column especialidad.especialidad
     *
     * @param especialidad the value for especialidad.especialidad
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column especialidad.idGrado
     *
     * @return the value of especialidad.idGrado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdgrado() {
        return idgrado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column especialidad.idGrado
     *
     * @param idgrado the value for especialidad.idGrado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdgrado(Integer idgrado) {
        this.idgrado = idgrado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column especialidad.idUsuario
     *
     * @return the value of especialidad.idUsuario
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdusuario() {
        return idusuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column especialidad.idUsuario
     *
     * @param idusuario the value for especialidad.idUsuario
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
}