package com.lab.sdt.model;

public class Estado {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estado.idEstado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idestado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estado.estado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String estado;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estado.idEstado
     *
     * @return the value of estado.idEstado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdestado() {
        return idestado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estado.idEstado
     *
     * @param idestado the value for estado.idEstado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdestado(Integer idestado) {
        this.idestado = idestado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estado.estado
     *
     * @return the value of estado.estado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estado.estado
     *
     * @param estado the value for estado.estado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }
}