package com.lab.sdt.model;

import java.util.Date;

public class ExpedienteConsulta {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expediente_consulta.idExpeConsul
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idexpeconsul;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expediente_consulta.fechaConsulta
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Date fechaconsulta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expediente_consulta.idExpediente
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idexpediente;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expediente_consulta.idExpeConsul
     *
     * @return the value of expediente_consulta.idExpeConsul
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdexpeconsul() {
        return idexpeconsul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expediente_consulta.idExpeConsul
     *
     * @param idexpeconsul the value for expediente_consulta.idExpeConsul
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdexpeconsul(Integer idexpeconsul) {
        this.idexpeconsul = idexpeconsul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expediente_consulta.fechaConsulta
     *
     * @return the value of expediente_consulta.fechaConsulta
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Date getFechaconsulta() {
        return fechaconsulta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expediente_consulta.fechaConsulta
     *
     * @param fechaconsulta the value for expediente_consulta.fechaConsulta
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setFechaconsulta(Date fechaconsulta) {
        this.fechaconsulta = fechaconsulta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expediente_consulta.idExpediente
     *
     * @return the value of expediente_consulta.idExpediente
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdexpediente() {
        return idexpediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expediente_consulta.idExpediente
     *
     * @param idexpediente the value for expediente_consulta.idExpediente
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdexpediente(Integer idexpediente) {
        this.idexpediente = idexpediente;
    }
}