package com.lab.sdt.model;

public class Grado {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grado.idGrado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idgrado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grado.grado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String grado;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grado.idGrado
     *
     * @return the value of grado.idGrado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdgrado() {
        return idgrado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grado.idGrado
     *
     * @param idgrado the value for grado.idGrado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdgrado(Integer idgrado) {
        this.idgrado = idgrado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grado.grado
     *
     * @return the value of grado.grado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getGrado() {
        return grado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grado.grado
     *
     * @param grado the value for grado.grado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setGrado(String grado) {
        this.grado = grado;
    }
}