package com.lab.sdt.model;

public class Hospital {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.idHospital
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idhospital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hospital
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String hospital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.calle
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String calle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.numero
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer numero;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.colonia
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String colonia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.codigoPostal
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String codigopostal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.idEstado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idestado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.telefono
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String telefono;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.estatus
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String estatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.idHospital
     *
     * @return the value of hospital.idHospital
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdhospital() {
        return idhospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.idHospital
     *
     * @param idhospital the value for hospital.idHospital
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdhospital(Integer idhospital) {
        this.idhospital = idhospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hospital
     *
     * @return the value of hospital.hospital
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getHospital() {
        return hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hospital
     *
     * @param hospital the value for hospital.hospital
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setHospital(String hospital) {
        this.hospital = hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.calle
     *
     * @return the value of hospital.calle
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getCalle() {
        return calle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.calle
     *
     * @param calle the value for hospital.calle
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setCalle(String calle) {
        this.calle = calle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.numero
     *
     * @return the value of hospital.numero
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getNumero() {
        return numero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.numero
     *
     * @param numero the value for hospital.numero
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.colonia
     *
     * @return the value of hospital.colonia
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getColonia() {
        return colonia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.colonia
     *
     * @param colonia the value for hospital.colonia
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.codigoPostal
     *
     * @return the value of hospital.codigoPostal
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getCodigopostal() {
        return codigopostal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.codigoPostal
     *
     * @param codigopostal the value for hospital.codigoPostal
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setCodigopostal(String codigopostal) {
        this.codigopostal = codigopostal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.idEstado
     *
     * @return the value of hospital.idEstado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdestado() {
        return idestado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.idEstado
     *
     * @param idestado the value for hospital.idEstado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdestado(Integer idestado) {
        this.idestado = idestado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.telefono
     *
     * @return the value of hospital.telefono
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.telefono
     *
     * @param telefono the value for hospital.telefono
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.estatus
     *
     * @return the value of hospital.estatus
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getEstatus() {
        return estatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.estatus
     *
     * @param estatus the value for hospital.estatus
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
}