package com.lab.sdt.model;

import java.util.ArrayList;
import java.util.List;

public class MantenimientoMaterialExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mantenimiento_material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mantenimiento_material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mantenimiento_material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mantenimiento_material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public MantenimientoMaterialExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mantenimiento_material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mantenimiento_material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mantenimiento_material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mantenimiento_material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mantenimiento_material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mantenimiento_material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mantenimiento_material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mantenimiento_material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mantenimiento_material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mantenimiento_material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mantenimiento_material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdmantematIsNull() {
            addCriterion("idManteMat is null");
            return (Criteria) this;
        }

        public Criteria andIdmantematIsNotNull() {
            addCriterion("idManteMat is not null");
            return (Criteria) this;
        }

        public Criteria andIdmantematEqualTo(Integer value) {
            addCriterion("idManteMat =", value, "idmantemat");
            return (Criteria) this;
        }

        public Criteria andIdmantematNotEqualTo(Integer value) {
            addCriterion("idManteMat <>", value, "idmantemat");
            return (Criteria) this;
        }

        public Criteria andIdmantematGreaterThan(Integer value) {
            addCriterion("idManteMat >", value, "idmantemat");
            return (Criteria) this;
        }

        public Criteria andIdmantematGreaterThanOrEqualTo(Integer value) {
            addCriterion("idManteMat >=", value, "idmantemat");
            return (Criteria) this;
        }

        public Criteria andIdmantematLessThan(Integer value) {
            addCriterion("idManteMat <", value, "idmantemat");
            return (Criteria) this;
        }

        public Criteria andIdmantematLessThanOrEqualTo(Integer value) {
            addCriterion("idManteMat <=", value, "idmantemat");
            return (Criteria) this;
        }

        public Criteria andIdmantematIn(List<Integer> values) {
            addCriterion("idManteMat in", values, "idmantemat");
            return (Criteria) this;
        }

        public Criteria andIdmantematNotIn(List<Integer> values) {
            addCriterion("idManteMat not in", values, "idmantemat");
            return (Criteria) this;
        }

        public Criteria andIdmantematBetween(Integer value1, Integer value2) {
            addCriterion("idManteMat between", value1, value2, "idmantemat");
            return (Criteria) this;
        }

        public Criteria andIdmantematNotBetween(Integer value1, Integer value2) {
            addCriterion("idManteMat not between", value1, value2, "idmantemat");
            return (Criteria) this;
        }

        public Criteria andIdmantenimientoIsNull() {
            addCriterion("idMantenimiento is null");
            return (Criteria) this;
        }

        public Criteria andIdmantenimientoIsNotNull() {
            addCriterion("idMantenimiento is not null");
            return (Criteria) this;
        }

        public Criteria andIdmantenimientoEqualTo(Integer value) {
            addCriterion("idMantenimiento =", value, "idmantenimiento");
            return (Criteria) this;
        }

        public Criteria andIdmantenimientoNotEqualTo(Integer value) {
            addCriterion("idMantenimiento <>", value, "idmantenimiento");
            return (Criteria) this;
        }

        public Criteria andIdmantenimientoGreaterThan(Integer value) {
            addCriterion("idMantenimiento >", value, "idmantenimiento");
            return (Criteria) this;
        }

        public Criteria andIdmantenimientoGreaterThanOrEqualTo(Integer value) {
            addCriterion("idMantenimiento >=", value, "idmantenimiento");
            return (Criteria) this;
        }

        public Criteria andIdmantenimientoLessThan(Integer value) {
            addCriterion("idMantenimiento <", value, "idmantenimiento");
            return (Criteria) this;
        }

        public Criteria andIdmantenimientoLessThanOrEqualTo(Integer value) {
            addCriterion("idMantenimiento <=", value, "idmantenimiento");
            return (Criteria) this;
        }

        public Criteria andIdmantenimientoIn(List<Integer> values) {
            addCriterion("idMantenimiento in", values, "idmantenimiento");
            return (Criteria) this;
        }

        public Criteria andIdmantenimientoNotIn(List<Integer> values) {
            addCriterion("idMantenimiento not in", values, "idmantenimiento");
            return (Criteria) this;
        }

        public Criteria andIdmantenimientoBetween(Integer value1, Integer value2) {
            addCriterion("idMantenimiento between", value1, value2, "idmantenimiento");
            return (Criteria) this;
        }

        public Criteria andIdmantenimientoNotBetween(Integer value1, Integer value2) {
            addCriterion("idMantenimiento not between", value1, value2, "idmantenimiento");
            return (Criteria) this;
        }

        public Criteria andIdmaterialIsNull() {
            addCriterion("idMaterial is null");
            return (Criteria) this;
        }

        public Criteria andIdmaterialIsNotNull() {
            addCriterion("idMaterial is not null");
            return (Criteria) this;
        }

        public Criteria andIdmaterialEqualTo(Integer value) {
            addCriterion("idMaterial =", value, "idmaterial");
            return (Criteria) this;
        }

        public Criteria andIdmaterialNotEqualTo(Integer value) {
            addCriterion("idMaterial <>", value, "idmaterial");
            return (Criteria) this;
        }

        public Criteria andIdmaterialGreaterThan(Integer value) {
            addCriterion("idMaterial >", value, "idmaterial");
            return (Criteria) this;
        }

        public Criteria andIdmaterialGreaterThanOrEqualTo(Integer value) {
            addCriterion("idMaterial >=", value, "idmaterial");
            return (Criteria) this;
        }

        public Criteria andIdmaterialLessThan(Integer value) {
            addCriterion("idMaterial <", value, "idmaterial");
            return (Criteria) this;
        }

        public Criteria andIdmaterialLessThanOrEqualTo(Integer value) {
            addCriterion("idMaterial <=", value, "idmaterial");
            return (Criteria) this;
        }

        public Criteria andIdmaterialIn(List<Integer> values) {
            addCriterion("idMaterial in", values, "idmaterial");
            return (Criteria) this;
        }

        public Criteria andIdmaterialNotIn(List<Integer> values) {
            addCriterion("idMaterial not in", values, "idmaterial");
            return (Criteria) this;
        }

        public Criteria andIdmaterialBetween(Integer value1, Integer value2) {
            addCriterion("idMaterial between", value1, value2, "idmaterial");
            return (Criteria) this;
        }

        public Criteria andIdmaterialNotBetween(Integer value1, Integer value2) {
            addCriterion("idMaterial not between", value1, value2, "idmaterial");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mantenimiento_material
     *
     * @mbg.generated do_not_delete_during_merge Mon May 20 14:45:29 CDT 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mantenimiento_material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}