package com.lab.sdt.model;

public class MantenimientoMaterial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mantenimiento_material.idManteMat
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idmantemat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mantenimiento_material.idMantenimiento
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idmantenimiento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mantenimiento_material.idMaterial
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idmaterial;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mantenimiento_material.idManteMat
     *
     * @return the value of mantenimiento_material.idManteMat
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdmantemat() {
        return idmantemat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mantenimiento_material.idManteMat
     *
     * @param idmantemat the value for mantenimiento_material.idManteMat
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdmantemat(Integer idmantemat) {
        this.idmantemat = idmantemat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mantenimiento_material.idMantenimiento
     *
     * @return the value of mantenimiento_material.idMantenimiento
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdmantenimiento() {
        return idmantenimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mantenimiento_material.idMantenimiento
     *
     * @param idmantenimiento the value for mantenimiento_material.idMantenimiento
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdmantenimiento(Integer idmantenimiento) {
        this.idmantenimiento = idmantenimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mantenimiento_material.idMaterial
     *
     * @return the value of mantenimiento_material.idMaterial
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdmaterial() {
        return idmaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mantenimiento_material.idMaterial
     *
     * @param idmaterial the value for mantenimiento_material.idMaterial
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdmaterial(Integer idmaterial) {
        this.idmaterial = idmaterial;
    }
}