package com.lab.sdt.model;

public class Material {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.idMaterial
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idmaterial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String material;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.idMaterial
     *
     * @return the value of material.idMaterial
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdmaterial() {
        return idmaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.idMaterial
     *
     * @param idmaterial the value for material.idMaterial
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdmaterial(Integer idmaterial) {
        this.idmaterial = idmaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.material
     *
     * @return the value of material.material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.material
     *
     * @param material the value for material.material
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setMaterial(String material) {
        this.material = material;
    }
}