package com.lab.sdt.model;

public class NumOnda {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column num_onda.idNum_Onda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idnumOnda;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column num_onda.idOnda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idonda;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column num_onda.idTipOnda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idtiponda;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column num_onda.idNum_Onda
     *
     * @return the value of num_onda.idNum_Onda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdnumOnda() {
        return idnumOnda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column num_onda.idNum_Onda
     *
     * @param idnumOnda the value for num_onda.idNum_Onda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdnumOnda(Integer idnumOnda) {
        this.idnumOnda = idnumOnda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column num_onda.idOnda
     *
     * @return the value of num_onda.idOnda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdonda() {
        return idonda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column num_onda.idOnda
     *
     * @param idonda the value for num_onda.idOnda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdonda(Integer idonda) {
        this.idonda = idonda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column num_onda.idTipOnda
     *
     * @return the value of num_onda.idTipOnda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdtiponda() {
        return idtiponda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column num_onda.idTipOnda
     *
     * @param idtiponda the value for num_onda.idTipOnda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdtiponda(Integer idtiponda) {
        this.idtiponda = idtiponda;
    }
}