package com.lab.sdt.model;

import java.util.ArrayList;
import java.util.List;

public class OndaValorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public OndaValorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdondavalorIsNull() {
            addCriterion("idOndaValor is null");
            return (Criteria) this;
        }

        public Criteria andIdondavalorIsNotNull() {
            addCriterion("idOndaValor is not null");
            return (Criteria) this;
        }

        public Criteria andIdondavalorEqualTo(Integer value) {
            addCriterion("idOndaValor =", value, "idondavalor");
            return (Criteria) this;
        }

        public Criteria andIdondavalorNotEqualTo(Integer value) {
            addCriterion("idOndaValor <>", value, "idondavalor");
            return (Criteria) this;
        }

        public Criteria andIdondavalorGreaterThan(Integer value) {
            addCriterion("idOndaValor >", value, "idondavalor");
            return (Criteria) this;
        }

        public Criteria andIdondavalorGreaterThanOrEqualTo(Integer value) {
            addCriterion("idOndaValor >=", value, "idondavalor");
            return (Criteria) this;
        }

        public Criteria andIdondavalorLessThan(Integer value) {
            addCriterion("idOndaValor <", value, "idondavalor");
            return (Criteria) this;
        }

        public Criteria andIdondavalorLessThanOrEqualTo(Integer value) {
            addCriterion("idOndaValor <=", value, "idondavalor");
            return (Criteria) this;
        }

        public Criteria andIdondavalorIn(List<Integer> values) {
            addCriterion("idOndaValor in", values, "idondavalor");
            return (Criteria) this;
        }

        public Criteria andIdondavalorNotIn(List<Integer> values) {
            addCriterion("idOndaValor not in", values, "idondavalor");
            return (Criteria) this;
        }

        public Criteria andIdondavalorBetween(Integer value1, Integer value2) {
            addCriterion("idOndaValor between", value1, value2, "idondavalor");
            return (Criteria) this;
        }

        public Criteria andIdondavalorNotBetween(Integer value1, Integer value2) {
            addCriterion("idOndaValor not between", value1, value2, "idondavalor");
            return (Criteria) this;
        }

        public Criteria andIdondaIsNull() {
            addCriterion("idOnda is null");
            return (Criteria) this;
        }

        public Criteria andIdondaIsNotNull() {
            addCriterion("idOnda is not null");
            return (Criteria) this;
        }

        public Criteria andIdondaEqualTo(Integer value) {
            addCriterion("idOnda =", value, "idonda");
            return (Criteria) this;
        }

        public Criteria andIdondaNotEqualTo(Integer value) {
            addCriterion("idOnda <>", value, "idonda");
            return (Criteria) this;
        }

        public Criteria andIdondaGreaterThan(Integer value) {
            addCriterion("idOnda >", value, "idonda");
            return (Criteria) this;
        }

        public Criteria andIdondaGreaterThanOrEqualTo(Integer value) {
            addCriterion("idOnda >=", value, "idonda");
            return (Criteria) this;
        }

        public Criteria andIdondaLessThan(Integer value) {
            addCriterion("idOnda <", value, "idonda");
            return (Criteria) this;
        }

        public Criteria andIdondaLessThanOrEqualTo(Integer value) {
            addCriterion("idOnda <=", value, "idonda");
            return (Criteria) this;
        }

        public Criteria andIdondaIn(List<Integer> values) {
            addCriterion("idOnda in", values, "idonda");
            return (Criteria) this;
        }

        public Criteria andIdondaNotIn(List<Integer> values) {
            addCriterion("idOnda not in", values, "idonda");
            return (Criteria) this;
        }

        public Criteria andIdondaBetween(Integer value1, Integer value2) {
            addCriterion("idOnda between", value1, value2, "idonda");
            return (Criteria) this;
        }

        public Criteria andIdondaNotBetween(Integer value1, Integer value2) {
            addCriterion("idOnda not between", value1, value2, "idonda");
            return (Criteria) this;
        }

        public Criteria andIdvalorIsNull() {
            addCriterion("idValor is null");
            return (Criteria) this;
        }

        public Criteria andIdvalorIsNotNull() {
            addCriterion("idValor is not null");
            return (Criteria) this;
        }

        public Criteria andIdvalorEqualTo(Integer value) {
            addCriterion("idValor =", value, "idvalor");
            return (Criteria) this;
        }

        public Criteria andIdvalorNotEqualTo(Integer value) {
            addCriterion("idValor <>", value, "idvalor");
            return (Criteria) this;
        }

        public Criteria andIdvalorGreaterThan(Integer value) {
            addCriterion("idValor >", value, "idvalor");
            return (Criteria) this;
        }

        public Criteria andIdvalorGreaterThanOrEqualTo(Integer value) {
            addCriterion("idValor >=", value, "idvalor");
            return (Criteria) this;
        }

        public Criteria andIdvalorLessThan(Integer value) {
            addCriterion("idValor <", value, "idvalor");
            return (Criteria) this;
        }

        public Criteria andIdvalorLessThanOrEqualTo(Integer value) {
            addCriterion("idValor <=", value, "idvalor");
            return (Criteria) this;
        }

        public Criteria andIdvalorIn(List<Integer> values) {
            addCriterion("idValor in", values, "idvalor");
            return (Criteria) this;
        }

        public Criteria andIdvalorNotIn(List<Integer> values) {
            addCriterion("idValor not in", values, "idvalor");
            return (Criteria) this;
        }

        public Criteria andIdvalorBetween(Integer value1, Integer value2) {
            addCriterion("idValor between", value1, value2, "idvalor");
            return (Criteria) this;
        }

        public Criteria andIdvalorNotBetween(Integer value1, Integer value2) {
            addCriterion("idValor not between", value1, value2, "idvalor");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table onda_valor
     *
     * @mbg.generated do_not_delete_during_merge Mon May 20 14:45:29 CDT 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table onda_valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}