package com.lab.sdt.model;

public class Onda {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onda.idOnda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idonda;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onda.nombre
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String nombre;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onda.idOnda
     *
     * @return the value of onda.idOnda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdonda() {
        return idonda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onda.idOnda
     *
     * @param idonda the value for onda.idOnda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdonda(Integer idonda) {
        this.idonda = idonda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onda.nombre
     *
     * @return the value of onda.nombre
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onda.nombre
     *
     * @param nombre the value for onda.nombre
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}