package com.lab.sdt.model;

public class OndaValor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onda_valor.idOndaValor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idondavalor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onda_valor.idOnda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idonda;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onda_valor.idValor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idvalor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onda_valor.idOndaValor
     *
     * @return the value of onda_valor.idOndaValor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdondavalor() {
        return idondavalor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onda_valor.idOndaValor
     *
     * @param idondavalor the value for onda_valor.idOndaValor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdondavalor(Integer idondavalor) {
        this.idondavalor = idondavalor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onda_valor.idOnda
     *
     * @return the value of onda_valor.idOnda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdonda() {
        return idonda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onda_valor.idOnda
     *
     * @param idonda the value for onda_valor.idOnda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdonda(Integer idonda) {
        this.idonda = idonda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onda_valor.idValor
     *
     * @return the value of onda_valor.idValor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdvalor() {
        return idvalor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onda_valor.idValor
     *
     * @param idvalor the value for onda_valor.idValor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdvalor(Integer idvalor) {
        this.idvalor = idvalor;
    }
}