package com.lab.sdt.model;

public class Parametro {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parametro.idParametro
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idparametro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parametro.frecuencia
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer frecuencia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parametro.amplitud
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String amplitud;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parametro.tiempo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String tiempo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parametro.idEquipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idequipo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parametro.idOnda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idonda;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parametro.idParametro
     *
     * @return the value of parametro.idParametro
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdparametro() {
        return idparametro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parametro.idParametro
     *
     * @param idparametro the value for parametro.idParametro
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdparametro(Integer idparametro) {
        this.idparametro = idparametro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parametro.frecuencia
     *
     * @return the value of parametro.frecuencia
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getFrecuencia() {
        return frecuencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parametro.frecuencia
     *
     * @param frecuencia the value for parametro.frecuencia
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setFrecuencia(Integer frecuencia) {
        this.frecuencia = frecuencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parametro.amplitud
     *
     * @return the value of parametro.amplitud
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getAmplitud() {
        return amplitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parametro.amplitud
     *
     * @param amplitud the value for parametro.amplitud
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setAmplitud(String amplitud) {
        this.amplitud = amplitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parametro.tiempo
     *
     * @return the value of parametro.tiempo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getTiempo() {
        return tiempo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parametro.tiempo
     *
     * @param tiempo the value for parametro.tiempo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setTiempo(String tiempo) {
        this.tiempo = tiempo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parametro.idEquipo
     *
     * @return the value of parametro.idEquipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdequipo() {
        return idequipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parametro.idEquipo
     *
     * @param idequipo the value for parametro.idEquipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdequipo(Integer idequipo) {
        this.idequipo = idequipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parametro.idOnda
     *
     * @return the value of parametro.idOnda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdonda() {
        return idonda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parametro.idOnda
     *
     * @param idonda the value for parametro.idOnda
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdonda(Integer idonda) {
        this.idonda = idonda;
    }
}