package com.lab.sdt.model;

public class Tipousuario {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipousuario.idTipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idtipo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipousuario.tipoUsuario
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String tipousuario;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipousuario.idTipo
     *
     * @return the value of tipousuario.idTipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdtipo() {
        return idtipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipousuario.idTipo
     *
     * @param idtipo the value for tipousuario.idTipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdtipo(Integer idtipo) {
        this.idtipo = idtipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipousuario.tipoUsuario
     *
     * @return the value of tipousuario.tipoUsuario
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getTipousuario() {
        return tipousuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipousuario.tipoUsuario
     *
     * @param tipousuario the value for tipousuario.tipoUsuario
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setTipousuario(String tipousuario) {
        this.tipousuario = tipousuario;
    }
}