package com.lab.sdt.model;

public class Ubicacion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion.idEstimulacion
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idestimulacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion.longuitud
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String longuitud;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion.latitud
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String latitud;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion.estatus
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String estatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion.idEstimulacion
     *
     * @return the value of ubicacion.idEstimulacion
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdestimulacion() {
        return idestimulacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion.idEstimulacion
     *
     * @param idestimulacion the value for ubicacion.idEstimulacion
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdestimulacion(Integer idestimulacion) {
        this.idestimulacion = idestimulacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion.longuitud
     *
     * @return the value of ubicacion.longuitud
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getLonguitud() {
        return longuitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion.longuitud
     *
     * @param longuitud the value for ubicacion.longuitud
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setLonguitud(String longuitud) {
        this.longuitud = longuitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion.latitud
     *
     * @return the value of ubicacion.latitud
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getLatitud() {
        return latitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion.latitud
     *
     * @param latitud the value for ubicacion.latitud
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion.estatus
     *
     * @return the value of ubicacion.estatus
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getEstatus() {
        return estatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion.estatus
     *
     * @param estatus the value for ubicacion.estatus
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
}