package com.lab.sdt.model;

public class Usuario {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.idUsuario
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idusuario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.nombre
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String nombre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.apellido1
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String apellido1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.apellido2
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String apellido2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.calle
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String calle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.num
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.colonia
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String colonia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.codigoPostal
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String codigopostal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.idEstado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idestado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.telefono
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String telefono;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.email
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.idTipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idtipo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.cuenta
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String cuenta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.contrasenia
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String contrasenia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.estatus
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String estatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.idUsuario
     *
     * @return the value of usuario.idUsuario
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdusuario() {
        return idusuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.idUsuario
     *
     * @param idusuario the value for usuario.idUsuario
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.nombre
     *
     * @return the value of usuario.nombre
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.nombre
     *
     * @param nombre the value for usuario.nombre
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.apellido1
     *
     * @return the value of usuario.apellido1
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getApellido1() {
        return apellido1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.apellido1
     *
     * @param apellido1 the value for usuario.apellido1
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.apellido2
     *
     * @return the value of usuario.apellido2
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getApellido2() {
        return apellido2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.apellido2
     *
     * @param apellido2 the value for usuario.apellido2
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.calle
     *
     * @return the value of usuario.calle
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getCalle() {
        return calle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.calle
     *
     * @param calle the value for usuario.calle
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setCalle(String calle) {
        this.calle = calle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.num
     *
     * @return the value of usuario.num
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.num
     *
     * @param num the value for usuario.num
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.colonia
     *
     * @return the value of usuario.colonia
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getColonia() {
        return colonia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.colonia
     *
     * @param colonia the value for usuario.colonia
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.codigoPostal
     *
     * @return the value of usuario.codigoPostal
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getCodigopostal() {
        return codigopostal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.codigoPostal
     *
     * @param codigopostal the value for usuario.codigoPostal
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setCodigopostal(String codigopostal) {
        this.codigopostal = codigopostal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.idEstado
     *
     * @return the value of usuario.idEstado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdestado() {
        return idestado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.idEstado
     *
     * @param idestado the value for usuario.idEstado
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdestado(Integer idestado) {
        this.idestado = idestado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.telefono
     *
     * @return the value of usuario.telefono
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.telefono
     *
     * @param telefono the value for usuario.telefono
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.email
     *
     * @return the value of usuario.email
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.email
     *
     * @param email the value for usuario.email
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.idTipo
     *
     * @return the value of usuario.idTipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdtipo() {
        return idtipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.idTipo
     *
     * @param idtipo the value for usuario.idTipo
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdtipo(Integer idtipo) {
        this.idtipo = idtipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.cuenta
     *
     * @return the value of usuario.cuenta
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getCuenta() {
        return cuenta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.cuenta
     *
     * @param cuenta the value for usuario.cuenta
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.contrasenia
     *
     * @return the value of usuario.contrasenia
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getContrasenia() {
        return contrasenia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.contrasenia
     *
     * @param contrasenia the value for usuario.contrasenia
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.estatus
     *
     * @return the value of usuario.estatus
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getEstatus() {
        return estatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.estatus
     *
     * @param estatus the value for usuario.estatus
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
}