package com.lab.sdt.model;

public class Valor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column valor.idValor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private Integer idvalor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column valor.valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    private String valor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column valor.idValor
     *
     * @return the value of valor.idValor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public Integer getIdvalor() {
        return idvalor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column valor.idValor
     *
     * @param idvalor the value for valor.idValor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setIdvalor(Integer idvalor) {
        this.idvalor = idvalor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column valor.valor
     *
     * @return the value of valor.valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public String getValor() {
        return valor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column valor.valor
     *
     * @param valor the value for valor.valor
     *
     * @mbg.generated Mon May 20 14:45:29 CDT 2019
     */
    public void setValor(String valor) {
        this.valor = valor;
    }
}